### ISSUE TITLE
What Other Models are Available?

### ISSUE THREAD

**Issue by RaghavMajorBoost** [Stability-AI/StableLM#46]
Hi All, I'm currently using the default AutoModelForCausalLM. What models would be recommended for a classifier? I'd like to write a system prompt to classify user inputs

**Comment by mcmonkey4eva** [comment]
Right now we've only publish StableLM, a text-prediction model (and of course Stable Diffusion and all that), I don't think we have any classifier models. There are definitely ones that exist out there somewhere. You'll have better luck searching externally rather than asking on the StableLM issues page though. Consider a google search, or asking in the Stable Foundation or LAION discords?
