### ISSUE TITLE
OSError: stabilityai/stablelm-base-alpha-3b-v2 does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.

### ISSUE THREAD

**Issue by RylanSchaeffer** [Stability-AI/StableLM#99]
When I try loading a StableLM, I get an OSError. Code from HuggingFace:

```
from transformers import AutoModelForCausalLM, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("stabilityai/stablelm-base-alpha-3b-v2")
model = AutoModelForCausalLM.from_pretrained(
  "stabilityai/stablelm-base-alpha-3b-v2",
  trust_remote_code=True,
  torch_dtype="auto",
)
```

Immediate error:

`OSError: stabilityai/stablelm-base-alpha-3b-v2 does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.`

Can someone please help me solve this?

**Comment by RylanSchaeffer** [comment]
I thought my `huggingface-hub` might be out of date, so I upgraded from 0.10.X to 0.16.4 and the error persists.

**Comment by jon-tow** [comment]
Hi, @RylanSchaeffer. Which version of `transformers` do you have installed? The model weights are stored as [safetensors](https://huggingface.co/docs/safetensors/index), and the `safetensors` package has become a core dependency of the lib since [v4.30.0](https://github.com/huggingface/transformers/releases/tag/v4.30.0). Try updating with:

```sh
pip install -U transformers
```

**Comment by RylanSchaeffer** [comment]
That seemed to do the trick - thank you!
